version: "3.9"

services:
  app:
    build:
      context: .
    command: >
      sh -c "
             python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000 
      "
    ports:
      - "8000:8000"
    volumes:
      - .:/Emarket
      - ./data/web:/vol/web
    env_file: .env
    environment:
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - ./dev-postgres-data:/var/lib/postgresql/data
    env_file: .env

