# Generated by Django 3.0.14 on 2022-04-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20220419_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='built_in_memory',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Memory (Gb)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='diagonal',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True, verbose_name='Diagonal (")'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, null=True, verbose_name='(%) disc.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_camera',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Camera (Mpx)'),
        ),
    ]
